[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
metadata = { path = "../metadata" }
serde = { workspace = true }
walkdir = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
redb = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
